background {
  monitor =
  path = ~/.config/wallpaper/paintings/502417ldsdl.jpg
  blur_passes = 1
  blur_size = 7
}

label {
  monitor =
  text = $TIME
  font_size = 100
  position = 0, -80
}

input-field {
  monitor =
  size = 20%, 5%
  font_family = JetBrainsMono Nerd Font
  dots_size = 0.08
}

